'use client';

import { useEffect, useRef, useState } from 'react';
import { useRouter } from 'next/navigation';
import { Button } from '@/components/ui/Button';
import { TabBar } from '@/components/chat/TabBar';
import { NeoSurface } from '@/components/ui/NeoSurface';
import { NeoInput } from '@/components/ui/NeoInput';
import { useAuth } from '@/lib/auth/AuthContext';
import { api, ApiError } from '@/lib/api/client';
import { idbGet } from '@/lib/storage/localDb';
import { initiateHandshake, toPublicBundle, DeviceIdentity, PublicKeyBundle } from '@/lib/crypto/engine';
import { initSession } from '@/lib/crypto/sessionStore';
import { normalizeUsername, validateUsername } from '@/lib/username';

const DURATIONS: { label: string; seconds: number | null }[] = [
  { label: '15m', seconds: 900 },
  { label: '1h', seconds: 3600 },
  { label: '1d', seconds: 86400 },
  { label: '7d', seconds: 604800 },
  { label: 'Forever', seconds: null },
];

interface FoundUser {
  username: string;
  displayName: string | null;
}
interface SearchResponse {
  user: FoundUser | null;
  isSelf?: boolean;
}

export default function ConnectPage() {
  const { userId } = useAuth();
  const router = useRouter();
  const [mode, setMode] = useState<'choose' | 'create' | 'enter' | 'username'>('choose');

  // --- Username-search flow ---
  // Finding someone here is only ever an identity/discovery step — it
  // never creates a conversation by itself. This app has no
  // "start a chat by user id" mechanism anywhere (every real
  // conversation is established by one side generating a pairing code
  // and the other redeeming it, which is also what drives the X3DH
  // handshake below), so once someone is found, this hands off into
  // exactly that same existing flow rather than inventing a second one.
  const [usernameQuery, setUsernameQuery] = useState('');
  const [searchResult, setSearchResult] = useState<SearchResponse | 'not-found' | null>(null);
  const [searching, setSearching] = useState(false);
  const searchRequestIdRef = useRef(0);

  const normalizedQuery = normalizeUsername(usernameQuery);
  const queryValidation = validateUsername(normalizedQuery);

  useEffect(() => {
    setSearchResult(null);
    if (!queryValidation.valid) return;
    const thisRequestId = ++searchRequestIdRef.current;
    setSearching(true);
    const timer = setTimeout(async () => {
      try {
        const result = await api<SearchResponse>(`/api/users/search?username=${encodeURIComponent(normalizedQuery)}`);
        if (searchRequestIdRef.current === thisRequestId) setSearchResult(result.user ? result : 'not-found');
      } catch {
        if (searchRequestIdRef.current === thisRequestId) setSearchResult('not-found');
      } finally {
        if (searchRequestIdRef.current === thisRequestId) setSearching(false);
      }
    }, 400);
    return () => clearTimeout(timer);
  }, [normalizedQuery, queryValidation.valid]);

  // Re-confirms discoverability right before handing off into the
  // pairing flow, rather than trusting the search result already on
  // screen — the target may have disabled username search, or blocked
  // this account, in the time since the search ran. Same endpoint, no
  // separate "confirm" API: calling it again immediately before acting
  // on it IS the confirmation (see UsersService.searchByUsername's own
  // comment on why there's exactly one code path for this).
  const [startChatError, setStartChatError] = useState<string | null>(null);
  const [confirmingStartChat, setConfirmingStartChat] = useState(false);
  async function handleStartChat(nextMode: 'create' | 'enter') {
    setStartChatError(null);
    setConfirmingStartChat(true);
    try {
      const result = await api<SearchResponse>(`/api/users/search?username=${encodeURIComponent(normalizedQuery)}`);
      if (!result.user) {
        setStartChatError('This account is no longer available to chat with.');
        setSearchResult('not-found');
        return;
      }
      setMode(nextMode);
    } catch {
      setStartChatError('Could not confirm this account right now. Please try again.');
    } finally {
      setConfirmingStartChat(false);
    }
  }

  // --- Create-code flow ---
  const [duration, setDuration] = useState<number | null>(900);
  const [generatedCode, setGeneratedCode] = useState<string | null>(null);
  // THE FIX (found during the final V1 feature-wiring audit): the create
  // response already includes pairingId — this just used to discard it.
  // "Forever" is a real, selectable duration right above, and the backend
  // already has a working DELETE /api/pairing/:id to revoke a code before
  // it's redeemed, but nothing in this page ever called it: once the user
  // navigated away from this screen, the code's id only ever lived in
  // local state, so a "Forever" code generated by mistake (or just no
  // longer wanted) had no way to be invalidated through the app, ever.
  // Keeping the id and wiring a Cancel button on this same screen closes
  // the actionable part of that gap — the moment right after creation,
  // while the code is still on screen. It doesn't solve revoking a code
  // *after* leaving this screen (no "list my pending codes" endpoint
  // exists to make that possible, and building one is a new capability,
  // not a wiring fix) — that residual gap is real and worth a product
  // decision, but out of this pass's scope.
  const [generatedPairingId, setGeneratedPairingId] = useState<string | null>(null);
  const [createError, setCreateError] = useState<string | null>(null);
  const [cancelling, setCancelling] = useState(false);

  // --- Enter-code flow ---
  const [digits, setDigits] = useState('');
  const [redeemError, setRedeemError] = useState<string | null>(null);
  const [redeeming, setRedeeming] = useState(false);

  async function handleCreate() {
    setCreateError(null);
    try {
      const result = await api<{ pairingId: string; code: string }>('/api/pairing/create', {
        method: 'POST',
        body: { durationSeconds: duration },
      });
      setGeneratedCode(result.code);
      setGeneratedPairingId(result.pairingId);
    } catch (e) {
      setCreateError(e instanceof ApiError ? e.message : 'Could not create a code. Please try again.');
    }
  }

  async function handleCancelCode() {
    if (!generatedPairingId) return;
    setCancelling(true);
    try {
      await api(`/api/pairing/${generatedPairingId}`, { method: 'DELETE' });
      setGeneratedCode(null);
      setGeneratedPairingId(null);
    } catch {
      setCreateError('Could not cancel the code. Please try again.');
    } finally {
      setCancelling(false);
    }
  }

  async function handleRedeem() {
    setRedeemError(null);
    if (!/^\d{6}$/.test(digits)) {
      setRedeemError('Enter the 6-digit code.');
      return;
    }
    setRedeeming(true);
    try {
      const identity = await idbGet<DeviceIdentity>('crypto:identity');
      if (!identity) throw new Error('No local device identity — please sign in again.');

      const result = await api<{ conversationId: string; bundle: PublicKeyBundle; sessionEpoch: number }>('/api/pairing/redeem', {
        method: 'POST',
        body: { code: digits },
      });

      const { session, message } = await initiateHandshake(identity, result.bundle);
      await api('/api/handshake', {
        method: 'POST',
        body: { conversationId: result.conversationId, handshakeMessage: message, sessionEpoch: result.sessionEpoch },
      });
      await initSession(result.conversationId, session, result.sessionEpoch);

      router.push(`/chat/${result.conversationId}`);
    } catch (e) {
      setRedeemError(e instanceof ApiError ? e.message : e instanceof Error ? e.message : 'Something went wrong.');
    } finally {
      setRedeeming(false);
    }
  }

  // Leaves the page entirely — distinct from the existing "← Back" control
  // further down, which only resets the in-page step (create/enter/
  // username -> choose) and is left untouched. `history.length > 1` is a
  // pragmatic signal for "there's somewhere in-app to return to"; Next's
  // router has no reliable way to know whether the previous entry was
  // actually within this app, so a direct link to /connect (history
  // length 1, e.g. opened in a new tab) falls back to the main screen
  // instead of leaving the user on a blank back-navigation.
  function handleBack() {
    if (typeof window !== 'undefined' && window.history.length > 1) {
      router.back();
    } else {
      router.push('/chat');
    }
  }

  return (
    <main className="flex min-h-screen flex-col p-6 pb-24 pt-[max(1rem,env(safe-area-inset-top))] lg:pb-8 lg:pl-56">
      <div className="mx-auto flex w-full max-w-sm flex-col gap-5 md:max-w-md">
        <header className="flex items-center gap-2 px-1 py-1">
        <Button
          variant="ghost"
          size="icon"
          aria-label="Go back"
          title="Go back"
          onClick={handleBack}
          className="!h-9 !w-9 shrink-0"
        >
          <svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" strokeWidth="2.25" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true">
            <path d="M15 18l-6-6 6-6" />
          </svg>
        </Button>
        <h1 className="text-xl font-bold">Connect</h1>
      </header>

      {mode === 'choose' && (
        <div className="flex flex-col gap-3">
          <Button variant="raised" className="w-full" onClick={() => setMode('create')}>
            Generate a code for someone to enter
          </Button>
          <Button variant="raised" className="w-full" onClick={() => setMode('enter')}>
            Enter a code someone gave me
          </Button>
          <Button variant="raised" className="w-full" onClick={() => setMode('username')}>
            Find someone by username
          </Button>
        </div>
      )}

      {mode === 'create' && (
        <NeoSurface variant="raised" className="flex flex-col gap-4 p-5">
          {!generatedCode ? (
            <>
              <div className="text-sm text-ink-dim">Expires in</div>
              <div className="flex flex-wrap gap-2">
                {DURATIONS.map((d) => (
                  <button
                    key={d.label}
                    onClick={() => setDuration(d.seconds)}
                    className={`rounded-full px-4 py-2 text-xs font-semibold ${
                      duration === d.seconds ? 'neo-pressed text-ink' : 'neo-raised text-ink-dim'
                    }`}
                  >
                    {d.label}
                  </button>
                ))}
              </div>
              {duration === null && (
                <div className="rounded-lg bg-surface-2 p-3 text-xs text-ink-dim">
                  Codes that never expire are a larger long-term target. Rate limiting still applies either way, but a
                  shorter duration is safer.
                </div>
              )}
              {createError && <div className="text-sm text-danger">{createError}</div>}
              <Button variant="glass" accent="info" className="w-full" onClick={handleCreate}>
                Generate code
              </Button>
            </>
          ) : (
            <>
              <div className="flex justify-center gap-2 font-mono text-3xl font-medium tracking-widest">
                {generatedCode}
              </div>
              <p className="text-center text-xs text-ink-dim">
                Share this with the one person you want to connect with. It works once.
              </p>
              {createError && <div className="text-center text-sm text-danger">{createError}</div>}
              <Button variant="raised" className="w-full" onClick={() => router.push('/chat')}>
                Done
              </Button>
              <Button variant="ghost" accent="danger" className="w-full" onClick={handleCancelCode} disabled={cancelling}>
                {cancelling ? 'Cancelling…' : 'Cancel this code'}
              </Button>
            </>
          )}
        </NeoSurface>
      )}

      {mode === 'username' && (
        <NeoSurface variant="raised" className="flex flex-col gap-4 p-5">
          <div className="relative">
            <span className="pointer-events-none absolute inset-y-0 left-4 flex items-center text-sm text-ink-dim">@</span>
            <NeoInput
              type="text"
              placeholder="username"
              value={usernameQuery}
              onChange={(e) => setUsernameQuery(e.target.value)}
              autoComplete="off"
              autoCapitalize="off"
              spellCheck={false}
              className="pl-8"
            />
          </div>

          {usernameQuery.length > 0 && !queryValidation.valid && (
            <div className="text-xs text-ink-dim">{queryValidation.error}</div>
          )}
          {searching && <div className="text-xs text-ink-dim">Searching…</div>}

          {searchResult === 'not-found' && !searching && <div className="text-sm text-ink-dim">User not found.</div>}

          {searchResult && searchResult !== 'not-found' && searchResult.isSelf && (
            <div className="text-sm text-ink-dim">This is your username.</div>
          )}

          {searchResult && searchResult !== 'not-found' && searchResult.user && !searchResult.isSelf && (
            <NeoSurface variant="pressed" className="flex flex-col gap-3 p-4">
              <div>
                <div className="text-sm font-semibold">@{searchResult.user.username}</div>
                {searchResult.user.displayName && <div className="text-xs text-ink-dim">{searchResult.user.displayName}</div>}
              </div>
              <p className="text-xs text-ink-dim">
                To start an encrypted chat, generate a code to share with them, or enter a code they&apos;ve shared with
                you.
              </p>
              {startChatError && <div className="text-xs text-danger">{startChatError}</div>}
              <div className="flex flex-col gap-2">
                <Button variant="glass" accent="info" className="w-full" onClick={() => handleStartChat('create')} disabled={confirmingStartChat}>
                  Generate a code to share
                </Button>
                <Button variant="raised" className="w-full" onClick={() => handleStartChat('enter')} disabled={confirmingStartChat}>
                  Enter their code
                </Button>
              </div>
            </NeoSurface>
          )}
        </NeoSurface>
      )}

      {mode === 'enter' && (
        <NeoSurface variant="raised" className="flex flex-col gap-4 p-5">
          <input
            value={digits}
            onChange={(e) => setDigits(e.target.value.replace(/\D/g, '').slice(0, 6))}
            placeholder="000000"
            inputMode="numeric"
            className="neo-pressed w-full rounded-lg py-4 text-center font-mono text-2xl tracking-[0.5em] text-ink focus:outline-none"
          />
          {redeemError && <div className="text-sm text-danger">{redeemError}</div>}
          <Button variant="glass" accent="info" className="w-full" onClick={handleRedeem} disabled={redeeming}>
            {redeeming ? 'Connecting…' : 'Connect'}
          </Button>
        </NeoSurface>
      )}

      {mode !== 'choose' && (
        <button className="text-center text-xs text-ink-dim" onClick={() => setMode('choose')}>
          ← Back
        </button>
      )}
      </div>

      <TabBar active="Connect" />
    </main>
  );
}
